Name: your-application-name           # 服务名称
Services:
  - Image: your-image                 # 服务镜像
    CPU: 0.5                          # CPU核心，最小为 0.1核心
    Memory: 500                       # 需要使用的内存，单位为 MiB
    Storage:                          # 是否需要挂载（可选）
      - Quantity: 500                   # 需要使用的挂载磁盘空间，单位为 MiB
        Persistent: true                # 永久存储，此值必须为 true
        Mount: "your/volume/path"       # 容器挂载的目录
    Ports:                            # 端口映射
      - Port: 80                      # 容器的内部端口
        ExposePort: 80                # 外部映射端口
    Env:                              # 环境变量（可选）
      YOUR_ENV_KEY: "YOUR_ENV_VALUE"
    Arguments:                        # 启动参数 (可选)
      - "--your-arg-key=your-arg-value"